# -*- coding: utf-8 -*-
"""clase 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiMJLl1S577Poc5cBcopXIbTtrdUBpOE
"""

#Registros financieros semestral
#ingreso  monto mensual
#uso un bucle para que se repita el ingreso 6 veces
i=1
ingreso_mensual=0
ingreso_total=0
for i in range(6):
  ingreso_mensual=float(input("Ingrese el monto del mes "))
  #validar monto positivo
  while ingreso_mensual < 0:
    ingreso_mensual=float(input("Por favor, ingrese el monto mensual "))
  ingreso_total=ingreso_total + ingreso_mensual

print(f"El ingreso total del semestre es de {ingreso_total}.-")