# -*- coding: utf-8 -*-
"""Clase 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccSK197wffkn9ne-Mog97Mph8vi2ZLfw
"""

nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
if (nombre)=="": #valido el ingreso de caracteres
  print("ERROR. No ha ingresado su nombre.")
apellido=input("Ahora introduce tu apellido ")# ingreso y guardo  caracteres
if (apellido)=="": #valido esta vex el ingreso de caracteres en apellido
  print("ERROR. No ha ingrsaso su apellido")
edad=input("Cual es tu edad?")
if int(edad )<=0: #compruebo una edad valida
  edad=input("ERROR. No ha ingresado una edad valida.")
else:
  if int(edad) < 18 and int(edad) >0:#valido que sea mayor de edad
    print("Es menor de edad")
email=input("Y finalmente, tu correo electronico ")
if (email)=="":#valido que se haya ingresado caracteres en email
        print("ERROR.No ha ingresado un e-mail valido")
print("Gracias!", end='\n')
#muestro los datos ingreados
print("Datos Introducidos\n Nombre:\t"+nombre+"   "+"Apellido:\t"+apellido+"\n Edad:\t"+edad+"\n E-Mail:\t"+email, end='\n')

#ejercicio 1 clase 03

nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
if len(nombre)==0: #valido el ingreso de caracteres
  print("ERROR. No ha ingresado su nombre.")
apellido=input("Ahora introduce tu apellido ")# ingreso y guardo  caracteres
if len(apellido)==0: #valido esta vex el ingreso de caracteres en apellido
  print("ERROR. No ha ingrsaso su apellido")
edad=input("Cual es tu edad?")
if int(edad )<=0: #compruebo una edad valida
  edad=input("ERROR. No ha ingresado una edad valida.")
else:
  if int(edad) < 18 and int(edad) >0:#valido que sea mayor de edad
    print("Es menor de edad")
email=input("Y finalmente, tu correo electronico ")
if len(email)==0:#valido que se haya ingresado caracteres en email
        print("ERROR.No ha ingresado un e-mail valido")
print("Gracias!", end='\n')
#muestro los datos ingreados
print("Datos Introducidos\n Nombre:\t"+nombre+"   "+"Apellido:\t"+apellido+"\n Edad:\t"+edad+"\n E-Mail:\t"+email, end='\n')

#ejercicio 1 clase 04

nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
if len(nombre)==0: #valido el ingreso de caracteres
  print("ERROR. No ha ingresado su nombre.")
apellido=input("Ahora introduce tu apellido ")# ingreso y guardo  caracteres
if len(apellido)==0: #valido esta vex el ingreso de caracteres en apellido
  print("ERROR. No ha ingrsaso su apellido")
#Validacion y clasificsscion de la edad

edad=input("Cual es tu edad? ")
if int(edad )<=0: #compruebo una edad valida
    edad=input("ERROR. No ha ingresado una edad valida.")
elif int(edad) > 18:
    rango_etario= "Adulto"
elif int(edad)<15:
    rango_etario= "Niño/a"
elif int(edad)>15 and int(edad) <18:
    rango_etario= "Adolescente"
#Validacion de Email
email=input("Y finalmente, tu correo electronico ")
if len(email)==0 or email.find("@")!="":#valido que se haya ingresado caracteres en email
   print("ERROR.No ha ingresado un e-mail valido")
print("Gracias!", end='\n')
#muestro los datos ingreados
# utilzo .strip() de quitar espacios al final y al principio
# Utilizo .lower() para colocar en minusculas los caracteres ingresados
# utilizo .title()para colocar en mayusculas las iniciales
print(f"Datos Introducidos\n Nombre:\t{nombre.lower().strip().title()}\t Apellido:\t {apellido.lower().strip().title()})\n Edad:\t{edad.strip()}\n Rango Etario:\t{rango_etario}\n E-Mail:\t{email.lower().strip()}")