# -*- coding: utf-8 -*-
"""tarjeta con color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kd40SeZV73R5izP013uYx95GvtxUzT46
"""

# Ingreso de los datos
nombre = input("Nombre: ")
apellido = input("Apellido: ")
email = input("Email: ")
edad = input("Edad: ")
# Colores para borde y texto
COLOR_MARCO = '\033[1;34m' # Azul en negrita
COLOR_TEXTO_NOMBRE = '\033[0;31m' # Nombre en rojo
COLOR_TEXTO_APELLIDO = '\033[1;31m' # Apellido en rojo negrita
COLOR_TEXTO_OTRO = '\033[0;32m' # Otros en verde
RESET_COLOR = '\033[0m' # Para volver al color normal
# tarjeta
print(f"{COLOR_MARCO}*********************************{RESET_COLOR}") # Borde superior
print(f"{COLOR_MARCO}|{RESET_COLOR} {COLOR_TEXTO_NOMBRE}Nombre: {nombre:<15}{RESET_COLOR} \t{COLOR_MARCO}|{RESET_COLOR}") # Nombre
print(f"{COLOR_MARCO}|{RESET_COLOR} {COLOR_TEXTO_APELLIDO}Apellido: {apellido:<15}{RESET_COLOR} \t{COLOR_MARCO}|{RESET_COLOR}") # Apellido
print(f"{COLOR_MARCO}|{RESET_COLOR} {COLOR_TEXTO_OTRO}Email: {email:<15}{RESET_COLOR} \t{COLOR_MARCO}|{RESET_COLOR}") # Email
print(f"{COLOR_MARCO}|{RESET_COLOR} {COLOR_TEXTO_OTRO}Edad: {edad:<15}{RESET_COLOR} \t{COLOR_MARCO}|{RESET_COLOR}") # Edad
print(f"{COLOR_MARCO}*********************************{RESET_COLOR}") # Borde inferior