# -*- coding: utf-8 -*-
"""Tarjeta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfEMIVksxDaCV4OWoFe2iNmhO7QmimQr
"""

nombre=input("Hola, te solicitaré tus datos, empezamos \n Introduce tu nombre ")
apellido=input("Ahora introduce tu apellido ")
edad=input("Cual es tu edad?)")
email=input("Y finalmente, tu correo electronico ")
print("Gracias !")
print("Datos Introducidos")
print("Nombre: " + nombre +" "+"Apellido: " + apellido)
print("Edad: " + edad)
print("E-Mail: " + email)

